#!/usr/bin/env bash
# This is a script to send a file to a client

if [$# -lt 4] then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

path = $1
server_ip = $2
username = $3
SSH_path = $4

scp -o "StrictHostKeyChecking no" -i "$path" "$SSH_path" "$username@$server_ip:~/"
