#!/usr/bin/env bash
#Script to print good luck,bad luck or Best school depending on condition

i=0
while ((i<10))
do
	if ((i==3))
	then
		echo "bad luck"
	elif ((i==7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i += 1))
done
